# Generated by Django 4.1.2 on 2023-01-04 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('gambar', models.CharField(max_length=40, null=True)),
                ('publikasi', models.DateField(null=True)),
                ('link', models.CharField(max_length=100)),
                ('sumber', models.CharField(max_length=100)),
                ('durasi', models.TimeField(null=True)),
                ('jenis_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='belajar_app.jenis')),
            ],
        ),
        migrations.CreateModel(
            name='Tempat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koordinat', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=40)),
                ('daya', models.TextField()),
                ('usaha_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='belajar_app.usaha')),
            ],
        ),
    ]
