# Generated by Django 4.1.2 on 2023-01-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajar_app', '0002_remove_video_durasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gambar',
            field=models.ImageField(null=True, upload_to='berita/'),
        ),
    ]
