# Generated by Django 4.1.2 on 2023-01-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belajar_app', '0003_alter_video_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gambar',
            field=models.FileField(null=True, upload_to='media/berita/'),
        ),
    ]
